// flow-typed signature: 68607c9482c933db9fb3d15ae2689209
// flow-typed version: <<STUB>>/babel-plugin-transform-react-pug_v4.x/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-pug/lib/__tests__/each-else.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/if-else.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/interpolation.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolated-component-error.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolation-error.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/js-invalid-expression-error.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/js-syntax-error.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/multi-line-plain-text.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/nested-loops.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/test-helper' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/text.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/update-const-error.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/__tests__/variable-declaration.test' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/babel-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/block-key' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/context' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/parse-pug' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/scope' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/add-loc-to-ast' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/add-string' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/interpolation' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/parse-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/parse-statement' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/utils/parse' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors.generated' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Case' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Code' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Conditional' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Each' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Tag' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/Text' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-pug/lib/visitors/While' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-pug/lib/__tests__/each-else.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/each-else.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/if-else.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/if-else.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/interpolation.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/interpolation.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolated-component-error.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolated-component-error.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolation-error.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/invalid-interpolation-error.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/js-invalid-expression-error.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/js-invalid-expression-error.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/js-syntax-error.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/js-syntax-error.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/multi-line-plain-text.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/multi-line-plain-text.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/nested-loops.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/nested-loops.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/test-helper.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/test-helper'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/text.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/text.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/update-const-error.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/update-const-error.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/__tests__/variable-declaration.test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/__tests__/variable-declaration.test'>;
}
declare module 'babel-plugin-transform-react-pug/lib/babel-types.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/babel-types'>;
}
declare module 'babel-plugin-transform-react-pug/lib/block-key.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/block-key'>;
}
declare module 'babel-plugin-transform-react-pug/lib/context.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/context'>;
}
declare module 'babel-plugin-transform-react-pug/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/index'>;
}
declare module 'babel-plugin-transform-react-pug/lib/parse-pug.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/parse-pug'>;
}
declare module 'babel-plugin-transform-react-pug/lib/scope.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/scope'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/add-loc-to-ast.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/add-loc-to-ast'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/add-string.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/add-string'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/interpolation.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/interpolation'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/parse-expression.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/parse-expression'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/parse-statement.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/parse-statement'>;
}
declare module 'babel-plugin-transform-react-pug/lib/utils/parse.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/utils/parse'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors.generated.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors.generated'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Case.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Case'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Code.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Code'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Conditional.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Conditional'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Each.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Each'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Tag.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Tag'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/Text.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/Text'>;
}
declare module 'babel-plugin-transform-react-pug/lib/visitors/While.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pug/lib/visitors/While'>;
}
